# Generated by Django 5.1.1 on 2025-07-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='IN_PROGRESS', max_length=12)),
                ('calling_status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('PENDING', 'Pending Approval')], default='ACTIVE', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this calling is currently active')),
                ('date_called', models.DateField(blank=True, default=None, help_text='Date when the calling was issued', null=True)),
                ('date_sustained', models.DateField(blank=True, help_text='Date when the calling was sustained', null=True)),
                ('date_set_apart', models.DateField(blank=True, help_text='Date when the member was set apart', null=True)),
                ('date_released', models.DateField(blank=True, help_text='Date when the calling was released', null=True)),
                ('calling_approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('NOT_REQUIRED', 'Not Required'), ('DECLINED', 'Declined')], default='PENDING', help_text='Approval status of the calling', max_length=15)),
                ('sustaining_approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('NOT_REQUIRED', 'Not Required'), ('DECLINED', 'Declined')], default='NOT_REQUIRED', help_text='Approval status of the sustaining', max_length=15)),
                ('setting_apart_approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('NOT_REQUIRED', 'Not Required'), ('DECLINED', 'Declined')], default='NOT_REQUIRED', help_text='Approval status of the setting apart', max_length=15)),
                ('released_approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('NOT_REQUIRED', 'Not Required'), ('DECLINED', 'Declined')], default='NOT_REQUIRED', help_text='Approval status of the release', max_length=15)),
                ('called_by', models.CharField(blank=True, help_text='Name of person who extended the calling', max_length=200, null=True)),
                ('presidency_approved', models.DateField(blank=True, help_text='Date when the presidency approved the calling', null=True)),
                ('hc_approved', models.DateField(blank=True, help_text='Date when the high council approved the calling', null=True)),
                ('bishop_consulted_by', models.CharField(blank=True, help_text='Name of bishop who was consulted for the calling', max_length=200, null=True)),
                ('lcr_updated', models.BooleanField(default=False, help_text='Whether this calling has been synced with LCR')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the calling', null=True)),
                ('release_notes', models.TextField(blank=True, help_text='Notes about the release of this calling', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Callings',
                'ordering': ['-date_called'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('leader', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this organization is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CallingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CALLED', 'Called'), ('RELEASED', 'Released'), ('UPDATED', 'Updated')], max_length=10)),
                ('member_name', models.CharField(blank=True, max_length=200, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('snapshot', models.JSONField()),
                ('calling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='callings.calling')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Calling History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of the position's responsibilities", null=True)),
                ('is_leadership', models.BooleanField(default=False, help_text='Whether this is a leadership position')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this position is currently active')),
                ('requires_setting_apart', models.BooleanField(default=False, help_text='Whether this position requires the member to be set apart')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order in which positions should be displayed (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='callings.organization')),
            ],
            options={
                'ordering': ['display_order', 'title'],
                'unique_together': {('title', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='calling',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callings', to='callings.position'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('WARD', 'Ward'), ('BRANCH', 'Branch'), ('STAKE', 'Stake')], max_length=10)),
                ('meeting_time', models.TimeField(blank=True, help_text='Regular meeting time for this unit', null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location of the unit', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this unit is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_units', to='callings.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='callings.unit'),
        ),
        migrations.AddField(
            model_name='calling',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callings', to='callings.unit'),
        ),
    ]
