# Generated by Django 5.1.1 on 2025-07-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calling',
            name='home_unit',
            field=models.CharField(blank=True, help_text='Home unit of the person (may differ from calling unit)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calling',
            name='proposed_replacement',
            field=models.CharField(blank=True, help_text='Name of the proposed replacement for this calling', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calling',
            name='released_by',
            field=models.CharField(blank=True, help_text='Name of person who released the calling', max_length=200, null=True),
        ),
    ]
