# Generated by Django 5.1.1 on 2025-07-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calling',
            name='date_called',
            field=models.DateField(blank=True, default=None, help_text='Date when the calling was issued', null=True),
        ),
        migrations.AlterField(
            model_name='calling',
            name='date_set_apart',
            field=models.DateField(blank=True, help_text='Date when the member was set apart', null=True),
        ),
        migrations.AlterField(
            model_name='calling',
            name='date_sustained',
            field=models.DateField(blank=True, help_text='Date when the calling was sustained', null=True),
        ),
    ]
