# Generated by Django 5.1.1 on 2025-07-09 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0002_calling_home_unit_calling_proposed_replacement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calling',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='callings', to='callings.organization'),
        ),
        migrations.RemoveField(
            model_name='position',
            name='organization',
        ),
    ]
