# Generated by Django 5.1.1 on 2025-07-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0002_alter_calling_date_called_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calling',
            name='calling_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('PENDING', 'Pending Approval')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='calling',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='IN_PROGRESS', max_length=12),
        ),
    ]
