# Generated by Django 5.1.1 on 2025-07-09 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0005_make_position_titles_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calling',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='callings', to='callings.organization'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
