# Generated by Django 5.1.1 on 2025-07-10 00:19

from django.db import migrations
from collections import defaultdict


def consolidate_position_titles(apps, schema_editor):
    Position = apps.get_model('callings', 'Position')
    Calling = apps.get_model('callings', 'Calling')
    
    # Group positions by base title (without numeric suffix)
    base_titles = defaultdict(list)
    
    for position in Position.objects.all():
        title_parts = position.title.split()
        # Check if the last part is a number
        if title_parts and title_parts[-1].isdigit():
            base_title = ' '.join(title_parts[:-1])  # Remove the numeric suffix
            base_titles[base_title].append(position)
        else:
            # Position doesn't have a numeric suffix, might be a base title
            base_titles[position.title].append(position)
    
    # For each base title that has multiple positions
    for base_title, positions in base_titles.items():
        if len(positions) > 1:
            print(f"Consolidating {len(positions)} positions for '{base_title}'")
            
            # Sort positions by ID to get consistent ordering
            positions.sort(key=lambda p: p.id)
            
            # Keep the first position as the primary one
            primary_position = positions[0]
            
            # Update the primary position's title to the base title (without suffix)
            if primary_position.title != base_title:
                primary_position.title = base_title
                primary_position.save()
                print(f"  Updated primary position to '{base_title}'")
            
            # Move all callings from duplicate positions to the primary position
            for duplicate_position in positions[1:]:
                callings_to_move = list(Calling.objects.filter(position=duplicate_position))
                if callings_to_move:
                    print(f"  Moving {len(callings_to_move)} callings from '{duplicate_position.title}' to '{base_title}'")
                    for calling in callings_to_move:
                        calling.position = primary_position
                        calling.save()
                
                # Delete the duplicate position
                print(f"  Deleting duplicate position '{duplicate_position.title}'")
                duplicate_position.delete()


def reverse_consolidate_position_titles(apps, schema_editor):
    # This migration cannot be easily reversed as we lose information
    # about which specific numbered position each calling was originally assigned to
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0007_cleanup_position_titles'),
    ]

    operations = [
        migrations.RunPython(
            consolidate_position_titles,
            reverse_consolidate_position_titles
        ),
    ]
