# Generated by Django 5.1.1 on 2025-07-10 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0008_consolidate_position_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calling',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callings', to='callings.organization'),
        ),
        migrations.AlterField(
            model_name='calling',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold'), ('LCR_UPDATED', 'LCR Updated')], default='IN_PROGRESS', max_length=12),
        ),
    ]
