# Generated by Django 5.1.1 on 2025-07-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0009_add_lcr_updated_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calling',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calling',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold'), ('LCR_UPDATED', 'LCR Updated')], default='PENDING', max_length=12),
        ),
    ]
