# Generated by Django 5.1.1 on 2025-07-10 01:16

from django.db import migrations, models
import django.db.models.deletion


def migrate_home_unit_data(apps, schema_editor):
    Calling = apps.get_model('callings', 'Calling')
    Unit = apps.get_model('callings', 'Unit')
    
    # Create a mapping dictionary for converting string names to Unit objects
    unit_mapping = {
        # Exact matches
        '13th Ward': 5,
        '5th Ward': 11,
        '6th Ward': 3,
        '8th Ward': 7,
        'Centennial': 12,
        'Centennial Ward': 9,
        'Harrison Ward': 4,
        'Hillcrest Ward': 1,
        'Lynwood Ward': 13,
        'Pillar Falls': 8,
        'Pillar Falls Ward': 10,
        'Stake': 2,
        'Swahili Branch': 6,
        
        # Abbreviated/alternate forms
        '13th': 5,
        '5th': 11,
        '6th': 3,
        '8th': 7,
        'Harrison': 4,
        'Lynwood': 13,
        'PF': 8,
        '20th Branch': None,  # No matching unit found
    }
    
    # Update all Calling objects
    for calling in Calling.objects.all():
        if calling.home_unit:
            unit_id = unit_mapping.get(calling.home_unit)
            if unit_id:
                try:
                    unit = Unit.objects.get(id=unit_id)
                    calling.home_unit_new = unit
                except Unit.DoesNotExist:
                    calling.home_unit_new = None
            # If no mapping found, home_unit_new will remain None
        calling.save()


def reverse_migrate_home_unit_data(apps, schema_editor):
    Calling = apps.get_model('callings', 'Calling')
    Unit = apps.get_model('callings', 'Unit')
    
    # Reverse mapping - convert Unit IDs back to strings
    reverse_mapping = {
        5: '13th Ward',
        11: '5th Ward',
        3: '6th Ward',
        7: '8th Ward',
        12: 'Centennial',
        9: 'Centennial Ward',
        4: 'Harrison Ward',
        1: 'Hillcrest Ward',
        13: 'Lynwood Ward',
        8: 'Pillar Falls',
        10: 'Pillar Falls Ward',
        2: 'Stake',
        6: 'Swahili Branch',
    }
    
    for calling in Calling.objects.all():
        if calling.home_unit_new:
            calling.home_unit = reverse_mapping.get(calling.home_unit_new.id, '')
        calling.save()


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0010_update_calling_status_and_fields'),
    ]

    operations = [
        # Step 1: Add the new ForeignKey field
        migrations.AddField(
            model_name='calling',
            name='home_unit_new',
            field=models.ForeignKey(
                blank=True,
                help_text='Home unit of the person (may differ from calling unit)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='home_members',
                to='callings.unit'
            ),
        ),
        
        # Step 2: Migrate the data
        migrations.RunPython(
            migrate_home_unit_data,
            reverse_migrate_home_unit_data
        ),
        
        # Step 3: Remove the old CharField
        migrations.RemoveField(
            model_name='calling',
            name='home_unit',
        ),
        
        # Step 4: Rename the new field to the original name
        migrations.RenameField(
            model_name='calling',
            old_name='home_unit_new',
            new_name='home_unit',
        ),
    ]
