# Generated by Django 5.1.1 on 2025-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0011_auto_20250709_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='unit',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order in which units should be displayed (lower numbers first)'),
        ),
    ]
