# Generated by Django 5.2.4 on 2025-07-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0012_add_sort_order_to_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calling',
            name='calling_approval_status',
        ),
        migrations.RemoveField(
            model_name='calling',
            name='calling_status',
        ),
        migrations.RemoveField(
            model_name='calling',
            name='sustaining_approval_status',
        ),
        migrations.AlterField(
            model_name='calling',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold'), ('CALLED', 'Called'), ('RELEASED', 'Released'), ('LCR_UPDATED', 'LCR Updated')], default='PENDING', max_length=12),
        ),
    ]
