# Generated by Django 5.2.4 on 2025-09-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0013_remove_calling_calling_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calling',
            name='released_approval_status',
        ),
        migrations.RemoveField(
            model_name='calling',
            name='setting_apart_approval_status',
        ),
        migrations.AlterField(
            model_name='calling',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold'), ('CALLED', 'Called'), ('LCR_UPDATED', 'LCR Updated')], default='PENDING', max_length=12),
        ),
    ]
