# Generated by Django 5.2.4 on 2025-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0014_remove_unused_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calling',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Stake Presidency Approved'), ('HC_APPROVED', 'High Council Approved'), ('ON_HOLD', 'On Hold'), ('CALLED', 'Called'), ('LCR_UPDATED', 'LCR Updated')], default='PENDING', max_length=12),
        ),
    ]
