# Generated by Django 5.2.4 on 2026-02-11 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings', '0015_update_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calling',
            index=models.Index(fields=['status', '-date_called'], name='calling_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calling',
            index=models.Index(fields=['unit', 'status'], name='calling_unit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='calling',
            index=models.Index(fields=['organization', 'status'], name='calling_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='calling',
            index=models.Index(fields=['is_active', 'status'], name='calling_active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='calling',
            index=models.Index(fields=['date_released'], name='calling_released_idx'),
        ),
        migrations.AddIndex(
            model_name='calling',
            index=models.Index(fields=['lcr_updated'], name='calling_lcr_idx'),
        ),
        migrations.AddIndex(
            model_name='callinghistory',
            index=models.Index(fields=['calling', '-changed_at'], name='history_calling_date_idx'),
        ),
        migrations.AddIndex(
            model_name='callinghistory',
            index=models.Index(fields=['action', '-changed_at'], name='history_action_date_idx'),
        ),
    ]
